# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_persona', models.CharField(max_length=1)),
                ('des_persona', models.CharField(max_length=100)),
                ('des_corta', models.CharField(max_length=30)),
                ('flag_cli', models.CharField(max_length=1)),
                ('flag_esp', models.CharField(max_length=1)),
                ('flag_prof', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=1000)),
                ('fec_nac', models.CharField(max_length=20)),
                ('cod_dpto', models.CharField(max_length=8)),
                ('cod_prov', models.CharField(max_length=8)),
                ('cod_dist', models.CharField(max_length=8)),
                ('nro_CIP', models.CharField(max_length=10)),
                ('fec_CIP_Vig', models.CharField(max_length=20)),
                ('centro_trabajo', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=20)),
                ('lic_cond', models.CharField(max_length=4)),
                ('obs', models.CharField(max_length=300)),
            ],
        ),
    ]
